"""Copy the Unity scripts and tests into a Unity project you created yourself.

The project must be created by Unity Hub so that ProjectSettings/ and Packages/
are generated by the editor rather than hand-written. This script only touches
the Assets tree, and deliberately does NOT create .meta files: Unity generates
them on import, which is the correct source for those files.

Run:
  python tools/unity-check/install_into_unity.py --project E:/智能家居/apps/unity-house
  python tools/unity-check/install_into_unity.py --project <path> --dry-run
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

REPO = Path(__file__).resolve().parents[2]
PAYLOAD = REPO / "apps" / "unity-house-payload" / "Assets"

# Files that indicate a real Unity project.
PROJECT_MARKERS = ("ProjectSettings/ProjectVersion.txt", "Assets")
GENERATED_DIRS = {"Library", "Temp", "Obj", "Logs", "UserSettings", "Build", "Builds"}


def is_unity_project(path: Path) -> tuple[bool, str]:
    if not path.exists():
        return False, "path does not exist"
    for marker in PROJECT_MARKERS:
        if not (path / marker).exists():
            return False, f"missing {marker}"
    return True, "ok"


def editor_version(project: Path) -> str | None:
    version_file = project / "ProjectSettings" / "ProjectVersion.txt"
    if not version_file.exists():
        return None
    for line in version_file.read_text(encoding="utf-8").splitlines():
        if line.startswith("m_EditorVersion:"):
            return line.split(":", 1)[1].strip()
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True, type=Path, help="path of the Unity project you created")
    parser.add_argument("--dry-run", action="store_true", help="show what would be copied")
    parser.add_argument("--force", action="store_true", help="overwrite existing files under Assets")
    args = parser.parse_args()

    project = args.project.expanduser().resolve()
    ok, reason = is_unity_project(project)
    if not ok:
        print(f"[FAIL] {project} does not look like a Unity project: {reason}")
        print("       Create it with Unity Hub first, then re-run this script.")
        return 2

    if not PAYLOAD.exists():
        print(f"[FAIL] payload missing: {PAYLOAD}")
        return 2

    version = editor_version(project)
    print(f"project : {project}")
    print(f"editor  : {version or '<unknown>'}")
    print(f"payload : {PAYLOAD}")
    print()

    planned: list[tuple[Path, Path]] = []
    for source in sorted(PAYLOAD.rglob("*")):
        if not source.is_file():
            continue
        relative = source.relative_to(PAYLOAD)
        planned.append((source, project / "Assets" / relative))

    if not planned:
        print("[FAIL] payload contains no files")
        return 2

    skipped = 0
    copied = 0
    for source, target in planned:
        display = target.relative_to(project).as_posix()
        if target.exists() and not args.force and not args.dry_run:
            print(f"  SKIP  {display} (already exists; use --force to overwrite)")
            skipped += 1
            continue
        print(f"  {'WOULD COPY' if args.dry_run else 'COPY '} {display}")
        if not args.dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            copied += 1

    print()
    if args.dry_run:
        print(f"dry run: {len(planned)} file(s) would be processed")
        return 0

    print(f"copied {copied}, skipped {skipped}")
    print()
    print("Next:")
    print("  1. Switch to the Unity editor window; it will import the scripts and")
    print("     generate .meta files automatically (this is expected and correct).")
    print("  2. Create an empty scene, add an empty GameObject, attach")
    print("     ConnectivityCheck.cs, then press Play.")
    print("  3. Start the home service first if you want a live connection:")
    print("     .venv\\Scripts\\python.exe apps/home-service/src/server.py --port 8765")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
